#GET http://localhost:8081/member/hello
#Accept: application/json

###

GET http://localhost:8000/member/member/count
Accept: application/json

###

POST http://localhost:8000/member/member/register
Content-Type: application/x-www-form-urlencoded

mobile=1

###

POST http://localhost:8000/member/member/sendCode
Content-Type: application/json

{
  "mobile":1123456789
}


###

POST http://localhost:8000/member/member/login
Content-Type: application/json

#注意必须要空格，不然会被识别为请求头
{
  "mobile":11234567890,
  "code":8888
}

> {%
client.log(JSON.stringify(response.body));
client.log(JSON.stringify(response.body.content.token));
client.global.set("token", response.body.content.token);
%}

###

