POST http://localhost:8000/member/passenger/save  #可以改成8001绕过gateway登录校验
Content-Type: application/json
token: {{token}}

{
  "name": "test",
  "idCard": "123321",
  "type": "1"
}

###

GET http://localhost:8000/member/passenger/queryList?page=1&size=2
Accept: application/json
token: {{token}}

###

POST http://localhost:8000/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "id": "1674027513409572864",
  "memberId": "1673320186188533760",
  "name": "test",
  "idCard": "100000",
  "type": "1"
}

###