POST http://localhost:8000/member/passenger/save  #可以改成8001绕过gateway登录校验
Content-Type: application/json
token: {{token}}

{
  "memberId": "12345678910",
  "name": "test",
  "idCard": "123321",
  "type": "1"
}

###

